### ISSUE TITLE
Fails to build detector_runner with Bazel >= 8

### ISSUE THREAD

**Issue by mathieu001** [google/vanir#6]
I have installed all the prerequisite tools mentioned in the Quick Start. Then I downloaded the latest Vanir and go to the Vanir directory. But I can't build the detector_runner correctly.

user@dev-machine:~/workspace/AOSP/sources/Android/vanir$ bazel build //:detector_runner
ERROR: Error computing the main repository mapping: error loading package 'external': Both --enable_bzlmod and --enable_workspace are disabled, but one of them must be enabled to fetch external dependencies.
Computing main repo mapping:

Then I checked .bazelrc and found '--enable_bzlmod' is False by default. I tried to change this it True but I got more errors when trying to build detector_runner. So how to build detector_runner? Any comments will be appreciated.

user@dev-machine:~/workspace/AOSP/sources/Android/vanir$ bazel build //:detector_runner
Starting local Bazel server and connecting to it...
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
WARNING: Target pattern parsing failed.
ERROR: Skipping '//:detector_runner': error loading package '': Unable to find package for @@[unknown repo 'vanir_deps' requested from @@]//:requirements.bzl: The repository '@@[unknown repo 'vanir_deps' requested from @@]' could not be resolved: No repository visible as '@vanir_deps' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration.
ERROR: error loading package '': Unable to find package for @@[unknown repo 'vanir_deps' requested from @@]//:requirements.bzl: The repository '@@[unknown repo 'vanir_deps' requested from @@]' could not be resolved: No repository visible as '@vanir_deps' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration.
INFO: Elapsed time: 9.092s
INFO: 0 processes.
ERROR: Build did NOT complete successfully

**Comment by baekhyunwook** [comment]
Thanks for sharing the issue with us! 
I guess it is due to the default value change for `--enable_workspace` introduced from [Bazel 8](https://bazel.build/external/migration) (released in 2024 Dec). 

Vanir is currently using `WORKSPACE.bazel` so the flag should be set to `True`. 
Could you retry running Vanir with `--enable_workspace=True`'? (or simply adding `common --enable_workspace=true` to `.bazelrc`).

**Comment by mathieu001** [comment]
Thank you so much for your reply!
I added `--enable_workspace=True` and got another error. Would you please help to have a look at it?

si@dev-machine:~/workspace/AOSP/sources/Android/vanir$ git diff
diff --git a/.bazelrc b/.bazelrc
index 30a9cb4..0ee46f1 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -5,5 +5,5 @@
 # https://developers.google.com/open-source/licenses/bsd


-common --enable_bzlmod=False
+common --enable_bzlmod=False --enable_workspace=True
 build --cxxopt=-std=c++17 --cxxopt=-fexceptions --cxxopt=-Wno-nonnull --cxxopt=-Wno-sign-compare --cxxopt=-Wno-parentheses --cxxopt=-Wno-deprecated-declarations
si@dev-machine:~/workspace/AOSP/sources/Android/vanir$ bazel build //:detector_runner
WARNING: WORKSPACE support will be removed in Bazel 9 (late 2025), please migrate to Bzlmod, see https://bazel.build/external/migration.
ERROR: /home/si/.cache/bazel/_bazel_si/14e04dbb2f510a16757e9795958221ee/external/rules_python/python/private/reexports.bzl:58:19: name 'PyInfo' is not defined (did you mean 'CcInfo'?)
ERROR: /home/si/.cache/bazel/_bazel_si/14e04dbb2f510a16757e9795958221ee/external/rules_python/python/private/reexports.bzl:61:26: name 'PyRuntimeInfo' is not defined
ERROR: Error computing the main repository mapping: at /home/si/.cache/bazel/_bazel_si/14e04dbb2f510a16757e9795958221ee/external/rules_python/python/pip.bzl:18:6: at /home/si/.cache/bazel/_bazel_si/14e04dbb2f510a16757e9795958221ee/external/rules_python/python/pip_install/requirements.bzl:3:6: at /home/si/.cache/bazel/_bazel_si/14e04dbb2f510a16757e9795958221ee/external/rules_python/python/defs.bzl:21:5: compilation of module 'python/private/reexports.bzl' failed
Computing main repo mapping:
    Fetching repository @@python3_9; starting
    Fetching repository @@bazel_skylib; starting

**Comment by baekhyunwook** [comment]
OK. I could reproduce your error after upgrading by Bazel to 8,
and it looks the Bazel 8, which was released yesterday, is causing a non-trivial compatibility issue.
I think this would take some time for us to fix.

Meanwhile, I would recommend you (and others) to try with Bazel 7.3.1 or lower.

If downgrading Bazel is complicated in your env, 
I would recommend to try [bazelisk ](https://github.com/bazelbuild/bazelisk?tab=readme-ov-file).
Once the bazelisk is installed, you can replace the `bazel` command in the tutorial with `bazelisk`. E.g.,
```
export USE_BAZEL_VERSION=7.4.1
bazelisk build //:detector_runner
bazelisk test --test_output=all //...
```

**Comment by baekhyunwook** [comment]
I will pin this issue until our team resolve this compatibility issue as it can affect other users trying Vanir with the recently released Bazel 8. @doryiii @jwdunlap for viz.

**Comment by mathieu001** [comment]
Thanks! It's indeed a compatibility issue. I have managed to build the detector successfully after downgrading Bazel to 7.3.1.
My AOSP source code is located at `~/workspace/sampleSdk/sources/Android` directory. I still got an error when trying to scan my this directory.

colinsi@b51b9e0822d2:~/workspace/sampleSdk/sources/Android/vanir$ ./bazel-bin/detector_runner repo_scanner Android ~/workspace/sampleSdk/sources/Android
I1211 11:42:35.336318 140267972717440 repo_scanner.py:117] Querying repo list...
I1211 11:42:39.443708 140267972717440 repo_scanner.py:140] Determining packages for each subdirectory...
I1211 11:42:58.517716 140267972717440 repo_scanner.py:170] Dir sources/Android/art maps to {'platform/art'}
I1211 11:42:58.518096 140267972717440 repo_scanner.py:170] Dir sources/Android/bionic maps to {'platform/bionic'}
I1211 11:42:58.518159 140267972717440 repo_scanner.py:170] Dir sources/Android/bootable/recovery maps to {'platform/bootable/recovery'}
I1211 11:42:58.518218 140267972717440 repo_scanner.py:170] Dir sources/Android/build/soong maps to {'platform/build/soong'}
I1211 11:42:58.518267 140267972717440 repo_scanner.py:170] Dir sources/Android/cts maps to {'platform/cts'}
I1211 11:42:58.518392 140267972717440 repo_scanner.py:170] Dir sources/Android/external/aac maps to {'platform/external/aac'}
...
I1211 11:42:58.525062 140267972717440 repo_scanner.py:170] Dir sources/Android/tools/apksig maps to {'platform/tools/apksig'}
I1211 11:42:58.525168 140267972717440 repo_scanner.py:183] 1206 dirs did not map to known packages
I1211 11:42:58.534063 140267972717440 repo_scanner.py:209] Running scans...
I1211 11:42:58.534180 140267972717440 repo_scanner.py:217] Scanning sources/Android/art (against {'platform/art'})
Traceback (most recent call last):
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/./bazel-bin/detector_runner.runfiles/vanir/detector_runner.py", line 529, in <module>
    app.run(main)
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/bazel-bin/detector_runner.runfiles/vanir_deps_absl_py/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/bazel-bin/detector_runner.runfiles/vanir_deps_absl_py/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/./bazel-bin/detector_runner.runfiles/vanir/detector_runner.py", line 465, in main
    findings, stats, vuln_manager = scanner.scan(
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/bazel-bin/detector_runner.runfiles/vanir/scanners/repo_scanner.py", line 222, in scan
    results[subdir] = self._scan_one_subdir(
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/bazel-bin/detector_runner.runfiles/vanir/scanners/repo_scanner.py", line 97, in _scan_one_subdir
    return scanner_base.scan(current_scan_path, signatures, strategy=strategy)
  File "/home/colinsi/workspace/sampleSdk/sources/Android/vanir/bazel-bin/detector_runner.runfiles/vanir/scanners/scanner_base.py", line 235, in scan
    raise ValueError(f'Invalid directory: {code_location}')
ValueError: Invalid directory: /home/colinsi/workspace/sampleSdk/sources/Android/sources/Android/art

**Comment by doryiii** [comment]
This has now been fixed.
